import { BookOpen, FileText, HelpCircle, Search, ChevronRight, ChevronDown, GraduationCap, DollarSign, Users, Grid, Activity, Database, Layers, FileCheck, Compass, GitCompareArrows } from 'lucide-react';
import HealthGuideIcon from '../components/brand/HealthGuideIcon';
import { useMemo, useState } from 'react';
import { useTranslation } from 'react-i18next';
import BackButton from '../components/BackButton';
import ServiceCatalogReference from '../components/ServiceCatalogReference';
import { serviceCategories, totalServiceCount } from '../data/services';
import { categoryAccent } from '../data/categoryTheme';
import { localizeCategory, localizeService } from '../lib/localizeServices';

interface LearningCenterProps {
  onNavigate: (page: string, data?: string) => void;
}

const glossaryTerms = [
  {
    term: 'Metabolic Age',
    meaning: 'A comparison between your biological metabolic efficiency and the average of your chronological age group',
    importance: 'A lower metabolic age suggests better cellular energy use and lower metabolic stress',
    helps: 'Guides lifestyle adjustments to improve long-term vitality and healthy weight regulation'
  },
  {
    term: 'Cortisol',
    meaning: 'A primary stress hormone regulating energy availability and alertness',
    importance: 'Chronically elevated levels impair sleep, mood, and metabolism',
    helps: 'Serves as a direct indicator of allostatic load and stress management needs'
  },
  {
    term: 'HRV (Heart Rate Variability)',
    meaning: 'The variation in time between heartbeats',
    importance: 'Higher HRV indicates better nervous system balance and recovery capacity',
    helps: 'Guides when to rest and when the body is ready to adapt to new challenges'
  },
  {
    term: 'Telomeres',
    meaning: 'Protective end-caps of DNA that shorten with stress and poor recovery',
    importance: 'Shorter telomeres signal faster aging and cellular decline',
    helps: 'Reflects long-term repair quality and biological aging rate'
  },
  {
    term: 'NAD+',
    meaning: 'A molecule essential for energy production and cellular repair',
    importance: 'Levels decline with age and stress, affecting cellular function',
    helps: 'Supports metabolic renewal and long-term vitality optimization'
  },
  {
    term: 'Autophagy',
    meaning: 'The body\'s natural "cellular cleanup" process that removes damaged cells',
    importance: 'Supports longevity and metabolic repair through cellular maintenance',
    helps: 'Used as a marker of cellular maintenance quality and regeneration'
  },
  {
    term: 'Biological Age',
    meaning: 'A measure of how old your body behaves functionally, not chronologically',
    importance: 'Tracks real aging processes, not calendar aging',
    helps: 'Encourages prevention before decline and tracks intervention effectiveness'
  },
  {
    term: 'BDNF',
    meaning: 'Brain-Derived Neurotrophic Factor - a molecule that supports neuroplasticity',
    importance: 'Higher BDNF improves learning, mood, and brain repair capacity',
    helps: 'Guides cognitive-performance routines and mental health optimization'
  },
  {
    term: 'Insulin Sensitivity',
    meaning: 'How effectively your cells respond to insulin to regulate blood sugar',
    importance: 'Higher sensitivity protects against metabolic syndrome and early aging',
    helps: 'Guides dietary timing and lifestyle interventions for metabolic health'
  },
  {
    term: 'Mitochondria',
    meaning: 'The "energy factories" inside cells that convert nutrients into ATP',
    importance: 'Strong mitochondrial function supports energy, longevity, and resilience',
    helps: 'Signals how well the body can power daily activity and recovery'
  },
  {
    term: 'Hormesis',
    meaning: 'Beneficial stress that strengthens the body when applied moderately',
    importance: 'Many longevity tools work through hormesis (cold, exercise, fasting)',
    helps: 'Clarifies why controlled stressors are helpful for adaptation'
  },
  {
    term: 'Neuroplasticity',
    meaning: 'The brain\'s ability to rewire and adapt throughout life',
    importance: 'Enables emotional healing, skill growth, and cognitive improvement',
    helps: 'Encourages training the nervous system through gradual adaptation'
  },
  {
    term: 'Multi-Model Intelligence',
    meaning: 'A report generated by two or more AI perspectives at the same time',
    importance: 'Combines physiological and behavioral viewpoints to reduce blind spots',
    helps: 'Improves clarity and creates a single, more reliable summary'
  },
  {
    term: 'Signal Coverage',
    meaning: 'How complete your inputs are across devices, questionnaires, notes, and reports',
    importance: 'Higher coverage creates more accurate interpretations',
    helps: 'Guides you on what to connect or update for better insights'
  },
  {
    term: 'Knowledge Snapshot',
    meaning: 'The current, condensed understanding of your health state',
    importance: 'Summarizes the most recent signals and history into a single view',
    helps: 'Keeps reports consistent and grounded in your real context'
  },
  {
    term: 'Consistency Delta',
    meaning: 'A comparison between what changed recently and what stayed stable',
    importance: 'Highlights meaningful shifts without overreacting to noise',
    helps: 'Improves confidence in decisions and reduces false alarms'
  },
  {
    term: 'Action Plan Builder',
    meaning: 'A structured plan generator for 7, 14, and 30-day steps',
    importance: 'Turns insights into realistic actions you can actually follow',
    helps: 'Makes progress measurable without overwhelming you'
  }
];

function stringList(value: unknown): string[] {
  return Array.isArray(value) ? value.filter((item): item is string => typeof item === 'string') : [];
}

export default function LearningCenter({ onNavigate }: LearningCenterProps) {
  const { t } = useTranslation();
  const [searchQuery, setSearchQuery] = useState('');
  const [selectedTerm, setSelectedTerm] = useState<string | null>(null);
  const [expandedSection, setExpandedSection] = useState<string | null>(null);
  const [expandedCategory, setExpandedCategory] = useState<string | null>(null);
  const localizedCategories = useMemo(
    () =>
      serviceCategories.map((category) => ({
        ...localizeCategory(t, category),
        services: category.services.map((service) =>
          localizeService(t, category.id, service),
        ),
      })),
    [t],
  );

  const filteredCategories = useMemo(() => {
    const q = searchQuery.toLowerCase().trim();
    if (!q) return localizedCategories;
    return localizedCategories.filter(
      (cat) =>
        cat.name.toLowerCase().includes(q) ||
        cat.description.toLowerCase().includes(q) ||
        cat.services.some(
          (s) => s.name.toLowerCase().includes(q) || s.description.toLowerCase().includes(q),
        ),
    );
  }, [localizedCategories, searchQuery]);

  const filteredTerms = glossaryTerms.filter(term =>
    term.term.toLowerCase().includes(searchQuery.toLowerCase()) ||
    term.meaning.toLowerCase().includes(searchQuery.toLowerCase())
  );

  const counts = { count: totalServiceCount(), categories: serviceCategories.length };

  const gettingStartedSections = [
    { key: 'pricing', icon: DollarSign },
    { key: 'member', icon: Users },
    { key: 'multiModel', icon: GitCompareArrows },
    { key: 'aiGuide', icon: BookOpen },
    { key: 'services', icon: FileText },
    { key: 'categories', icon: Grid },
    { key: 'signalHub', icon: BookOpen },
  ] as const;

  return (
    <div className="min-h-screen bg-page pt-20 pb-16">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <BackButton onNavigate={onNavigate} />

        <div className="text-center mb-12">
          <div className="inline-flex items-center justify-center w-16 h-16 bg-orange-600 rounded-2xl mb-4 shadow-lg shadow-orange-600/20">
            <GraduationCap className="h-8 w-8 text-white" />
          </div>
          <h1 className="text-4xl font-bold text-gray-900 dark:text-neutral-100 mb-4">
            {t('learning.title')}
          </h1>
          <p className="text-lg text-gray-600 dark:text-neutral-300 max-w-3xl mx-auto">
            {t('learning.subtitle')}
          </p>
        </div>

        <div className="mb-12">
          <div className="relative max-w-2xl mx-auto">
            <Search className="absolute left-4 top-1/2 -translate-y-1/2 h-5 w-5 text-gray-500 dark:text-neutral-400" />
            <input
              type="text"
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              placeholder={t('learning.searchPlaceholder')}
              className="w-full pl-12 pr-4 py-4 rounded-xl border border-[var(--bm-border)] bg-surface text-gray-900 dark:text-neutral-100 placeholder:text-gray-500 dark:placeholder:text-neutral-400 focus:ring-2 focus:ring-orange-600 focus:border-transparent shadow-sm"
            />
          </div>
        </div>

        <div className="grid lg:grid-cols-3 gap-8 mb-12">
          <div className="lg:col-span-2 space-y-8">
            <div className="bg-surface rounded-xl p-8 border border-[var(--bm-border)] shadow-sm">
              <div className="flex items-center space-x-3 mb-6">
                <BookOpen className="h-6 w-6 text-orange-600 dark:text-orange-400" />
                <h2 className="text-2xl font-bold text-gray-900 dark:text-neutral-100">
                  {t('learning.gettingStarted')}
                </h2>
              </div>

              <div className="space-y-3">
                {gettingStartedSections.map((section) => {
                  const Icon = section.icon;
                  const isExpanded = expandedSection === section.key;

                  return (
                    <div key={section.key} className="border border-[var(--bm-border)] rounded-lg overflow-hidden bg-page">
                      <button
                        onClick={() => setExpandedSection(isExpanded ? null : section.key)}
                        className="w-full flex items-center justify-between p-4 bg-page hover:bg-slate-100/80 dark:hover:bg-[var(--bm-surface)] transition-colors"
                      >
                        <div className="flex items-center space-x-3">
                          <Icon className="h-5 w-5 text-orange-600 dark:text-orange-400" />
                          <span className="font-medium text-gray-900 dark:text-neutral-100">
                            {t(`learning.sections.${section.key}.title`)}
                          </span>
                        </div>
                        {isExpanded ? (
                          <ChevronDown className="h-5 w-5 text-gray-500 dark:text-neutral-400" />
                        ) : (
                          <ChevronRight className="h-5 w-5 text-gray-500 dark:text-neutral-400" />
                        )}
                      </button>
                      {isExpanded && (
                        <div className="p-4 bg-surface border-t border-[var(--bm-border)]">
                          <p className="text-sm text-gray-600 dark:text-neutral-300 leading-relaxed">
                            {t(`learning.sections.${section.key}.body`, counts)}
                          </p>
                          {section.key === 'pricing' && (
                            <button
                              onClick={() => onNavigate('services')}
                              className="mt-4 text-sm text-orange-600 dark:text-orange-400 hover:underline"
                            >
                              {t('learning.viewPlans')}
                            </button>
                          )}
                          {section.key === 'member' && (
                            <button
                              onClick={() => onNavigate('member')}
                              className="mt-4 text-sm text-orange-600 dark:text-orange-400 hover:underline"
                            >
                              {t('learning.goToMember')}
                            </button>
                          )}
                          {section.key === 'services' && (
                            <button
                              onClick={() => onNavigate('services-catalog')}
                              className="mt-4 text-sm text-orange-600 dark:text-orange-400 hover:underline"
                            >
                              {t('learning.browseServices')}
                            </button>
                          )}
                        </div>
                      )}
                    </div>
                  );
                })}
              </div>
            </div>

            <div className="bg-gradient-to-br from-[#1a1e25] via-[#1e232b] to-[#252b34] rounded-2xl p-8 text-white border border-white/15 shadow-lg">
              <div className="flex items-center space-x-3 mb-6">
                <HealthGuideIcon
                  className="h-10 w-10 rounded-xl shadow-md shadow-orange-600/40"
                  size={40}
                />
                <h2 className="text-2xl font-bold">{t('learning.ai.title')}</h2>
              </div>
              <p className="text-sm text-slate-200 max-w-2xl">
                {t('learning.ai.intro')}
              </p>

              <div className="mt-6 grid md:grid-cols-5 gap-4">
                {[
                  { key: 'intake', icon: Activity },
                  { key: 'snapshot', icon: Database },
                  { key: 'analysis', icon: Layers },
                  { key: 'report', icon: FileCheck },
                  { key: 'plan', icon: Compass },
                ].map((step, index) => {
                  const Icon = step.icon;
                  return (
                  <div key={step.key} className="rounded-xl bg-white/10 border border-white/15 p-4">
                    <div className="text-xs uppercase tracking-widest text-orange-300 mb-2">
                      {t('learning.ai.step', { number: index + 1 })}
                    </div>
                    <div className="flex items-center gap-2 mb-2">
                      <Icon className="h-4 w-4 text-orange-300" />
                      <div className="font-semibold">{t(`learning.ai.steps.${step.key}.title`)}</div>
                    </div>
                    <div className="text-xs text-slate-200 mt-1">
                      {t(`learning.ai.steps.${step.key}.desc`)}
                    </div>
                  </div>
                );
                })}
              </div>

              <div className="mt-6 flex flex-col sm:flex-row gap-3">
                <button
                  onClick={() => onNavigate('reports')}
                  className="px-5 py-3 rounded-lg bg-orange-600 hover:bg-orange-500 text-white font-semibold text-sm transition-colors"
                >
                  {t('learning.ai.viewExample')}
                </button>
                <button
                  onClick={() => onNavigate('second-opinion-demo')}
                  className="px-5 py-3 rounded-lg bg-white/10 hover:bg-white/20 text-white font-semibold text-sm transition-colors"
                >
                  {t('learning.ai.exploreSecondOpinion')}
                </button>
              </div>

              <div className="mt-6 grid md:grid-cols-2 gap-4">
                <div className="rounded-xl border border-white/15 bg-white/10 p-5">
                  <div className="flex items-center justify-between mb-3">
                    <div className="text-xs uppercase tracking-widest text-orange-300">
                      {t('learning.ai.exampleLabel')}
                    </div>
                    <div className="text-xs text-slate-200">{t('learning.ai.unifiedSummary')}</div>
                  </div>
                  <div className="text-lg font-semibold">{t('learning.ai.exampleTitle')}</div>
                  <p className="text-sm text-slate-200 mt-2">
                    {t('learning.ai.exampleBody')}
                  </p>
                  <div className="mt-4 grid grid-cols-3 gap-3">
                    <div className="rounded-lg bg-black/20 p-3 text-center">
                      <div className="text-xs text-slate-200">{t('learning.ai.quality')}</div>
                      <div className="text-lg font-semibold text-white">92%</div>
                    </div>
                    <div className="rounded-lg bg-black/20 p-3 text-center">
                      <div className="text-xs text-slate-200">{t('learning.ai.coverage')}</div>
                      <div className="text-lg font-semibold text-white">87%</div>
                    </div>
                    <div className="rounded-lg bg-black/20 p-3 text-center">
                      <div className="text-xs text-slate-200">{t('learning.ai.consistency')}</div>
                      <div className="text-lg font-semibold text-white">+6%</div>
                    </div>
                  </div>
                </div>

                <div className="rounded-xl border border-white/15 bg-white/10 p-5">
                  <div className="text-xs uppercase tracking-widest text-orange-300 mb-3">
                    {t('learning.ai.planLabel')}
                  </div>
                  <div className="text-lg font-semibold">{t('learning.ai.planTitle')}</div>
                  <ul className="mt-3 space-y-2 text-sm text-slate-200">
                    {stringList(t('learning.ai.planItems', { returnObjects: true })).map((item) => (
                      <li key={item}>{item}</li>
                    ))}
                  </ul>
                  <div className="mt-4 rounded-lg bg-black/20 p-3 text-xs text-slate-200">
                    {t('learning.ai.focusTag')}
                  </div>
                </div>
              </div>

              <div className="mt-6 rounded-2xl border border-white/15 bg-white/10 p-5">
                <div className="text-xs uppercase tracking-widest text-orange-300 mb-4">
                  {t('learning.ai.secondOpinionLabel')}
                </div>
                <div className="grid md:grid-cols-3 gap-4">
                  <div className="rounded-xl border border-white/15 bg-white/10 p-4">
                    <div className="text-xs text-slate-200 mb-2">{t('learning.ai.modelA')}</div>
                    <div className="font-semibold">{t('learning.ai.modelATitle')}</div>
                    <p className="text-xs text-slate-200 mt-2">
                      {t('learning.ai.modelABody')}
                    </p>
                  </div>
                  <div className="rounded-xl border border-white/15 bg-white/10 p-4">
                    <div className="text-xs text-slate-200 mb-2">{t('learning.ai.modelB')}</div>
                    <div className="font-semibold">{t('learning.ai.modelBTitle')}</div>
                    <p className="text-xs text-slate-200 mt-2">
                      {t('learning.ai.modelBBody')}
                    </p>
                  </div>
                  <div className="rounded-xl border border-orange-400/30 bg-gradient-to-br from-orange-500/10 to-white/5 p-4">
                    <div className="text-xs text-orange-200 mb-2">
                      {t('learning.ai.unifiedSummary')}
                    </div>
                    <div className="font-semibold">{t('learning.ai.unifiedTitle')}</div>
                    <p className="text-xs text-slate-200 mt-2">
                      {t('learning.ai.unifiedBody')}
                    </p>
                  </div>
                </div>
                <div className="mt-4 rounded-xl border border-white/15 bg-white/10 p-4 text-xs text-slate-200">
                  {t('learning.ai.howToRead')}
                </div>
              </div>
            </div>

            <div className="bg-surface rounded-xl p-8 border border-[var(--bm-border)] shadow-sm">
              <div className="flex items-center space-x-3 mb-6">
                <Grid className="h-6 w-6 text-orange-600 dark:text-orange-400" />
                <h2 className="text-2xl font-bold text-gray-900 dark:text-neutral-100">
                  {t('learning.categoriesTitle')}
                </h2>
              </div>
              <p className="text-gray-600 dark:text-neutral-300 mb-6">
                {t('learning.categoriesIntro', counts)}
              </p>

              <div className="space-y-3">
                {filteredCategories.map((category) => {
                  const open = expandedCategory === category.id;
                  const accent = categoryAccent(category.id);
                  const q = searchQuery.toLowerCase().trim();
                  const services = q
                    ? category.services.filter(
                        (s) =>
                          s.name.toLowerCase().includes(q) ||
                          s.description.toLowerCase().includes(q) ||
                          category.name.toLowerCase().includes(q),
                      )
                    : category.services;

                  return (
                    <div
                      key={category.id}
                      className="border border-[var(--bm-border)] rounded-lg bg-page shadow-sm overflow-hidden"
                    >
                      <button
                        type="button"
                        onClick={() => setExpandedCategory(open ? null : category.id)}
                        className="w-full p-4 text-left hover:bg-slate-100 dark:hover:bg-gray-800 transition-colors"
                      >
                        <div className="flex items-center justify-between gap-2">
                          <div className="min-w-0 flex-1">
                            <div className="flex flex-wrap items-center gap-x-3 gap-y-1 mb-1">
                              <span
                                className="font-semibold tracking-tight"
                                style={{ color: accent }}
                              >
                                {category.name}
                              </span>
                              <span className="text-xs text-gray-500 dark:text-neutral-400">
                                {t('learning.servicesCount', { count: category.services.length })}
                              </span>
                            </div>
                            <p className="text-xs text-gray-600 dark:text-neutral-300">{category.description}</p>
                          </div>
                          {open ? (
                            <ChevronDown className="h-5 w-5 text-orange-600 dark:text-orange-400 flex-shrink-0" />
                          ) : (
                            <ChevronRight className="h-5 w-5 text-gray-500 dark:text-neutral-400 flex-shrink-0" />
                          )}
                        </div>
                      </button>
                      {open && (
                        <div className="border-t border-[var(--bm-border)] bg-surface px-4 py-3 space-y-3">
                          {services.map((service) => (
                            <div key={service.id} className="border-l-2 pl-3" style={{ borderColor: `${accent}66` }}>
                              <p className="text-sm font-semibold text-gray-900 dark:text-neutral-100">{service.name}</p>
                              <p className="mt-0.5 text-xs leading-relaxed text-gray-600 dark:text-neutral-300">
                                {service.description}
                              </p>
                            </div>
                          ))}
                          <button
                            type="button"
                            onClick={() => onNavigate('services-catalog', category.id)}
                            className="text-sm font-semibold text-orange-600 dark:text-orange-400 hover:underline"
                          >
                            {t('learning.openInCatalog')}
                          </button>
                        </div>
                      )}
                    </div>
                  );
                })}
              </div>
            </div>
          </div>

          <div className="space-y-6">
            <div className="bg-gradient-to-br from-orange-600 to-orange-700 rounded-xl p-6 text-white shadow-lg">
              <div className="flex items-center space-x-3 mb-4">
                <div className="inline-flex h-10 w-10 items-center justify-center rounded-xl bg-white shadow-sm">
                  <HealthGuideIcon className="h-7 w-7" size={28} />
                </div>
                <h3 className="text-xl font-bold">{t('learning.guide.title')}</h3>
              </div>
              <p className="text-orange-100 mb-4 text-sm">
                {t('learning.guide.body')}
              </p>
              <button
                onClick={() => onNavigate('member')}
                className="w-full px-4 py-3 bg-white text-orange-700 hover:bg-orange-50 rounded-lg transition-colors font-medium text-sm"
              >
                {t('learning.guide.cta')}
              </button>
            </div>

            <div className="bg-surface rounded-xl p-6 border border-[var(--bm-border)] shadow-sm">
              <div className="flex items-center space-x-3 mb-4">
                <FileText className="h-6 w-6 text-orange-600 dark:text-orange-400" />
                <h3 className="text-lg font-bold text-gray-900 dark:text-neutral-100">
                  {t('learning.secondOpinion.title')}
                </h3>
              </div>
              <p className="text-sm text-gray-600 dark:text-neutral-300 mb-4">
                {t('learning.secondOpinion.body')}
              </p>
              <button
                onClick={() => onNavigate('second-opinion-demo')}
                className="w-full text-left px-4 py-3 bg-page hover:bg-slate-100 dark:hover:bg-[var(--bm-page)]/80 rounded-lg transition-colors text-sm text-gray-700 dark:text-gray-300"
              >
                {t('learning.secondOpinion.cta')}
              </button>
            </div>

            <div className="bg-surface rounded-xl p-6 border border-[var(--bm-border)] shadow-sm">
              <div className="flex items-center space-x-3 mb-4">
                <HelpCircle className="h-6 w-6 text-orange-600 dark:text-orange-400" />
                <h3 className="text-lg font-bold text-gray-900 dark:text-neutral-100">
                  {t('learning.quickHelp.title')}
                </h3>
              </div>
              <button
                onClick={() => onNavigate('faq')}
                className="w-full text-left px-4 py-3 bg-page hover:bg-slate-100 dark:hover:bg-[var(--bm-page)]/80 rounded-lg transition-colors text-sm text-gray-700 dark:text-gray-300"
              >
                {t('learning.quickHelp.cta')}
              </button>
            </div>
          </div>
        </div>

        <div className="mb-12">
          <ServiceCatalogReference
            title={t('learning.referenceTitle')}
            subtitle={t('learning.referenceSubtitle', counts)}
            onOpenCategory={(categoryId) => onNavigate('services-catalog', categoryId)}
            includeHumanDataModel
          />
        </div>

        <div className="bg-surface rounded-xl p-8 border border-[var(--bm-border)] shadow-sm mb-12">
          <div className="flex items-center space-x-3 mb-6">
            <BookOpen className="h-6 w-6 text-orange-600 dark:text-orange-400" />
            <h2 className="text-2xl font-bold text-gray-900 dark:text-neutral-100">
              {t('learning.glossaryTitle')}
            </h2>
          </div>
          <p className="text-gray-600 dark:text-neutral-300 mb-6">
            {t('learning.glossaryIntro')}
          </p>

          <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-4">
            {filteredTerms.map((item, index) => {
              const isExpanded = selectedTerm === item.term;

              return (
                <button
                  key={index}
                  onClick={() => setSelectedTerm(isExpanded ? null : item.term)}
                  className="text-left p-4 rounded-lg bg-page hover:bg-slate-100 dark:hover:bg-[var(--bm-page)]/80 transition-colors border border-[var(--bm-border)] shadow-sm"
                >
                  <h4 className="font-semibold text-gray-900 dark:text-neutral-100 mb-2">{item.term}</h4>
                  <p className="text-sm text-gray-600 dark:text-neutral-300 mb-2">{item.meaning}</p>

                  {isExpanded && (
                    <div className="mt-3 pt-3 border-t border-[var(--bm-border)] space-y-2">
                      <div>
                        <p className="text-xs font-medium text-orange-600 dark:text-orange-400 mb-1">
                          {t('learning.whyItMatters')}
                        </p>
                        <p className="text-xs text-gray-600 dark:text-neutral-300">{item.importance}</p>
                      </div>
                      <div>
                        <p className="text-xs font-medium text-orange-700 dark:text-orange-400 mb-1">
                          {t('learning.howItHelps')}
                        </p>
                        <p className="text-xs text-gray-600 dark:text-neutral-300">{item.helps}</p>
                      </div>
                    </div>
                  )}
                </button>
              );
            })}
          </div>
        </div>

        <div className="bg-surface rounded-xl p-8 text-center border border-[var(--bm-border)]">
          <h2 className="text-2xl font-bold text-gray-900 dark:text-neutral-100 mb-4">
            {t('learning.philosophy.title')}
          </h2>
          <p className="text-gray-600 dark:text-neutral-300 max-w-3xl mx-auto mb-8">
            {t('learning.philosophy.body')}
          </p>
          <div className="grid md:grid-cols-3 gap-6 max-w-4xl mx-auto">
            <div className="bg-surface rounded-xl p-6 border border-[var(--bm-border)] shadow-sm">
              <p className="font-semibold text-gray-900 dark:text-neutral-100 mb-2">
                {t('learning.philosophy.whatTitle')}
              </p>
              <p className="text-sm text-gray-600 dark:text-neutral-300">
                {t('learning.philosophy.whatBody')}
              </p>
            </div>
            <div className="bg-surface rounded-xl p-6 border border-[var(--bm-border)] shadow-sm">
              <p className="font-semibold text-gray-900 dark:text-neutral-100 mb-2">
                {t('learning.philosophy.howTitle')}
              </p>
              <p className="text-sm text-gray-600 dark:text-neutral-300">
                {t('learning.philosophy.howBody')}
              </p>
            </div>
            <div className="bg-surface rounded-xl p-6 border border-[var(--bm-border)] shadow-sm">
              <p className="font-semibold text-gray-900 dark:text-neutral-100 mb-2">
                {t('learning.philosophy.goalTitle')}
              </p>
              <p className="text-sm text-gray-600 dark:text-neutral-300">
                {t('learning.philosophy.goalBody')}
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
